# Generated by Django 4.0.6 on 2025-05-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AveDePresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(default='Fisioterapeuta Aviar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SesionFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField()),
                ('descripcion', models.TextField()),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.avedepresa')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.empleado')),
            ],
        ),
    ]
